apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: demo-dentsu-application
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/charantechi/argocd-node-app-config.git
    targetRevision: HEAD
    path: node-app
  destination: 
    server: https://kubernetes.default.svc
    namespace: demo-stag-app

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true
