apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-node-app
spec:
  selector:
    matchLabels:
      app: demo-node-app
  replicas: 2
  template:
    metadata:
      labels:
        app: demo-node-app
    spec:
      containers:
        - name: demo-node-app
          image: dentsupaymentsstgacr.azurecr.io/dpnode-stag:7
          ports:
            - containerPort: 3000
